name: Simple Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo remotely
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.HIDDEN_REPO }}
          path: /
          token: ${{ secrets.TOKEN }}
      - name: Show hidden files
        run: |
          cd /
          ls
      - name: Print message
        run: echo "Build completed successfully!"
